from setuptools import setup, find_packages

setup(
    name="isit2025-wireless-wanderlust",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "tensorflow>=2.12.0",
        "numpy>=1.19.5",
        "pandas>=1.4.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.2",
        "scikit-learn>=1.0.2",
        "scipy>=1.7.3",
        "pytest>=7.0.0",
        "black>=22.3.0",
        "flake8>=4.0.1",
        "isort>=5.10.1",
        "jupyter>=1.0.0",
        "notebook>=6.4.12",
        "tqdm>=4.64.0",
        "pillow>=9.0.0",
        "h5py>=3.7.0",
        "PyYAML>=6.0",
        "requests>=2.28.0",
        "typing-extensions>=4.4.0",
        "protobuf>=3.20.0",
        "tensorboard>=2.12.0"
    ],
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="ISIT 2025 Wireless Wanderlust Competition Solution",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/isit2025-wireless-wanderlust",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
) 